// <auto-generated />
using System;
using KooliProjekt.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KooliProjekt.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251128082420_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KooliProjekt.Application.Data.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alguskuupaev")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kirjeldus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lopetatuskuupaev")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nimi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projektid");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToDoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToDoListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToDoListId");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Tootaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ametikoht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tootajad");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Ylesanne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kirjeldus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pealkiri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int");

                    b.Property<string>("Staatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tahtaeg")
                        .HasColumnType("datetime2");

                    b.Property<int>("TootajaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TunnidKokku")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjektId");

                    b.HasIndex("TootajaId");

                    b.ToTable("Ylesanded");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.ToDoItem", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.ToDoList", "ToDoList")
                        .WithMany()
                        .HasForeignKey("ToDoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDoList");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Ylesanne", b =>
                {
                    b.HasOne("KooliProjekt.Application.Data.Projekt", "Projekt")
                        .WithMany("Ylesanded")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KooliProjekt.Application.Data.Tootaja", "Tootaja")
                        .WithMany("Ylesanded")
                        .HasForeignKey("TootajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekt");

                    b.Navigation("Tootaja");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Projekt", b =>
                {
                    b.Navigation("Ylesanded");
                });

            modelBuilder.Entity("KooliProjekt.Application.Data.Tootaja", b =>
                {
                    b.Navigation("Ylesanded");
                });
#pragma warning restore 612, 618
        }
    }
}
